[package]
type = 'bash'
name = 'woof'
slug = 'woof'
version = '0.3.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'The version manager to end all version managers'

[run]
dependencies = ['https://github.com/hyperupcall/bats-all@v4.3.0', 'https://github.com/hyperupcall/bash-core.git@v0.3.2', 'https://github.com/hyperupcall/bash-tty.git@v0.3.0']
sourceDirs = ['pkg/src/commands', 'pkg/src/util']
builtinDirs = []
binDirs = ['pkg/bin']
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
pipefail = 'on'

[run.shoptOptions]
shift_verbose = 'on'
