[package]
type = 'app'
name = 'woof'
slug = 'woof'
version = '0.4.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'The version manager to end all version managers'

[run]
dependencies = [
	'https://github.com/hyperupcall/bats-all@v4.6.0',
	'https://github.com/hyperupcall/bash-core@v0.12.0',
	'https://github.com/hyperupcall/bash-term@v0.6.3',
	'https://github.com/hyperupcall/bash-utility@v0.3.0',
]
sourceDirs = ['pkg/src/util']
builtinDirs = []
binDirs = ['pkg/bin']
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
pipefail = 'on'

[run.shoptOptions]
shift_verbose = 'on'
