[package]
type = 'bash'
name = 'woof'
slug = 'woof'
version = '0.4.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'The version manager to end all version managers'

[run]
dependencies = [
	'https://github.com/hyperupcall/bats-all@v4.3.0',
	'https://github.com/hyperupcall/bash-core@v0.11.0',
	'https://github.com/hyperupcall/bash-term@v0.6.2',
	'https://github.com/hyperupcall/bash-std@v0.2.1',
]
sourceDirs = ['pkg/src/commands', 'pkg/src/util']
builtinDirs = []
binDirs = ['pkg/bin']
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
pipefail = 'on'

[run.shoptOptions]
shift_verbose = 'on'
